name: Setup environment
description: Set up Python, uv, and Nox

inputs:
  python-version:
    description: Python version to install
    required: true

runs:
  using: composite
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "0.10.6"

    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v6.2.0
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install Nox
      shell: bash
      run: |
        uv tool install nox --with uv
        nox --version
